# Generated by Django 5.1.5 on 2025-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical Notes'), ('board', 'Board Exam Notes')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='pdf_notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
